#pragma once

enum {
    RECORDER_MODE_BASEBAND,
    RECORDER_MODE_AUDIO,
    RECORDER_MODE_PUREIQ
};

enum DemodID {
    RADIO_DEMOD_NFM,
    RADIO_DEMOD_WFM,
    RADIO_DEMOD_AM,
    RADIO_DEMOD_DSB,
    RADIO_DEMOD_USB,
    RADIO_DEMOD_CW,
    RADIO_DEMOD_LSB,
    RADIO_DEMOD_RAW,
    RADIO_DEMOD_IQ
};
